### ISSUE TITLE
Bower unable to correctly solve dependencies due to packages conflicts

### ISSUE THREAD

**Issue by ThomasG77** [MapStory/story-tools#100]
Doing an

    npm install
    bower install

I get an error about dependencies solving error e.g

>    Unable to find a suitable version for angular, please choose one:
>        1) angular#1.2.21 which resolved to 1.2.21 and is required by time-controls 
>        2) angular#>=1 which resolved to 1.2.21 and is required by angular-bootstrap#0.11.2 
>        3) angular#1.3.8 which resolved to 1.3.8 and is required by angular-mocks#1.3.8Prefix the choice with ! to persist it to bower.json

**Comment by bartvde** [comment]
right this is a known issue picking any of those options should work though

**Comment by ischneider** [comment]
FYI, 1.2.21 is targeted for compatibility with the eventual integration with MapLoom.
