### ISSUE TITLE
remove button for classes does not work

### ISSUE THREAD

**Issue by bartvde** [MapStory/story-tools#102]
doesn't seem to do anything, not sure if it ever did @ischneider or that I broke something?

![screen shot 2015-01-16 at 15 40 27](https://cloud.githubusercontent.com/assets/319678/5777802/12c8ae84-9d96-11e4-86e7-0cf29e79cde1.png)

**Comment by ischneider** [comment]
Never did anything. Sorry, should have added a not-implemented message or such.

**Comment by ischneider** [comment]
Closing w/ new related issues
