### ISSUE TITLE
complete polygon styles

### ISSUE THREAD

**Issue by ischneider** [MapStory/story-tools#112]
As per designs:

* simple
* unique
* choropleth

**Comment by ischneider** [comment]
@bartvde vector simple seems to work okay, had problems with classify (rules evaluated but not rendered) but didn't get to looking into

SLD definitely not dealt w/ at this point - polygon style handling is not implemented yet

**Comment by bartvde** [comment]
right I can confirm the issue @ischneider will investigate

**Comment by bartvde** [comment]
ah this is simply not implemented, just like line wasn't before #109
