### ISSUE TITLE
move map config parsing into separate service

### ISSUE THREAD

**Issue by bartvde** [MapStory/story-tools#127]
and test it as well

**Comment by bartvde** [comment]
@ischneider where would this service go? I guess in core but it doesn't really match any of the existing subcategories?

**Comment by ischneider** [comment]
I think for now perhaps it's best to make a mapstory module? I was thinking that other parts of the examples could benefit from linting and testing so if/when that happens we can add an examples module.

Later we can extract to another project/bundle if it seems worth it.
