### ISSUE TITLE
hook up story-pins editor to playback

### ISSUE THREAD

**Issue by ischneider** [MapStory/story-tools#135]
Based on our 'protocol', this means:

* set `timeAttribute` property on layer
* use `features` property on layer to store annotations

See also #134

**Comment by bartvde** [comment]
The disadvantage here of using the same approach is that we'll need to keep the features param in sync. For normal vector layers this is no issue since we load all features upon first load. But maybe this is no big deal.

**Comment by ischneider** [comment]
Added as part of 0ad37ef, closing.
