### ISSUE TITLE
support start/end date in filterVectorLayer

### ISSUE THREAD

**Issue by ischneider** [MapStory/story-tools#136]
Currently filtering only works on a single instant and not a range

this implies we can either:
* get both start/end attribute for vector layers OR
* allow the user to specify start/end attributes and parse them client-side

The former is convenient provided we have the configuration (via geoserver/geonode internals) but the latter allows for 3rd party vector data as a fallback.

**Comment by bartvde** [comment]
with range you are referring to the data here right? Not so much the range for playback right?

**Comment by ischneider** [comment]
Right, this is for features with a range of start/end attributes. I was looking at the annotations and realized this was needed.

**Comment by ischneider** [comment]
Filtering and vector range computation (for layers lacking time configuration) added with 0ad37ef as part of storypins work.

Closing this without addressing the ability to specify attributes. That can come later.
