### ISSUE TITLE
clearing / adding of features is bottleneck in vector playback

### ISSUE THREAD

**Issue by bartvde** [MapStory/story-tools#141]
as reported by @ischneider 

not a major deal but on the walmart layer I noticed it was kinda jerky. the time filtering only takes ~10 ms but clearing/adding takes up to ~150ms

Check to use FeatureOverlay instead of see if we can add an option to the ```ol.layer.Vector``` to bypass the spatial index

**Comment by bartvde** [comment]
see also: https://github.com/openlayers/ol3/issues/2386

**Comment by bartvde** [comment]
okay there are issues with using a FeatureOverlay. It cannot store arbitrary options for instance, such as url.

**Comment by bartvde** [comment]
hmm I've changed the underlying implementation not to use a spatial index but don't see much improvement

**Comment by bartvde** [comment]
although the call to clear and add is now instantaneous (1 or 0)

```
    var start = new Date().getTime();
    layer.getSource().clear(true);
    layer.getSource().addFeatures(features);
    var end = new Date().getTime();
    window.console.log(end-start);
```

**Comment by bartvde** [comment]
so maybe it's improved after all

**Comment by bartvde** [comment]
WIP for ol3 is here:

https://github.com/bartvde/ol3/compare/vector-bypass-rtree

**Comment by bartvde** [comment]
one thing I noticed is that clear wasn't using the fast option so I opened up: https://github.com/openlayers/ol3/pull/3201/files

**Comment by bartvde** [comment]
it would also be good if we had a way not to use ServerVector, since it provided quite a bit of overhead as well

**Comment by bartvde** [comment]
okay found a way not to have to use ServerVector

**Comment by ischneider** [comment]
@bartvde, 29540a9 seems to have reduced my worse case times by a non-scientific 20-30%. Should we leave open for follow up on the fast clean and spatial index bypass?

**Comment by bartvde** [comment]
ah that's good news
fast clean is not needed anymore, since we now don't use ServerVector anymore we don't have that issue

Spatial index bypass did not seem to make any positive difference, so I guess we can close this.

Thanks for testing @ischneider
