### ISSUE TITLE
wps errors not handled totally

### ISSUE THREAD

**Issue by ischneider** [MapStory/story-tools#144]
I added a mapstory layer and attempted a choropleth style. Since the WPS processes aren't on that server, there is an exception response. While we'll eventually have the correct WPS processes installed, we should still handle exception responses better.

**Comment by bartvde** [comment]
yeah the error is in the console, but we should inform the user as well

```Unknown process vec:FeatureClassStats```

**Comment by bartvde** [comment]
what is your recommendation for the dialog here @ischneider 
I've used http://bootboxjs.com before but not sure if you would want to pull that in.

**Comment by bartvde** [comment]
@ischneider suggested modal from: http://angular-ui.github.io/bootstrap/

**Comment by bartvde** [comment]
I've created a template like:

```
<div>
    <div class="modal-header">
        <h3 class="modal-title">{{title}}</h3>
    </div>
    <div class="modal-body">
       <span>{{msg}}</span>
    </div>
    <div class="modal-footer">
        <button class="btn btn-primary" ng-click="ok()">OK</button>
        <button class="btn btn-warning" ng-click="cancel()">Cancel</button>
    </div>
</div>
```

But failing to understand how to pass on the variables in this case ......

```
                                $modal.open({
                                    templateUrl: '/lib/templates/core/dialog.html'
                                });
```

**Comment by ischneider** [comment]
@bartvde I think you just need to provide a scope object as part of the options to `open`. The default is to use the `$rootScope`

**Comment by bartvde** [comment]
right I actually tried something like that but to no avail

**Comment by ischneider** [comment]
It does look like it wants an actual scope object. You can create this using something like

```javascript
        var scope = $rootScope.$new(true);
        scope.title = 'title';
        scope.body = 'body'
        $modal.open({
            templateUrl: 'myModalContent.html',
            scope: scope
        });
```

or using a controller that populates the scope
```javascript
        $modal.open({
            templateUrl: 'myModalContent.html',
            controller: function($scope) {
                $scope.title = 'title';
                $scope.body = 'body';
            }
        });
```

if you only have an 'OK' button, like for an error dialog, you can do this in the template since the `$close` function is available

```html
<button class="btn btn-primary" ng-click="$close()">OK</button>
```

**Comment by bartvde** [comment]
Yeah I actually tried the first approach, will try it again

**Comment by bartvde** [comment]
Got it to work with the controller approach thanks for the help @ischneider
