### ISSUE TITLE
see if we can filter attributes for choropleth to only numeric

### ISSUE THREAD

**Issue by bartvde** [MapStory/story-tools#159]
this does not apply to unique though

**Comment by bartvde** [comment]
@ischneider any pointers on how to achieve this? So we would need to change the ```include``` based on the classification method used

**Comment by ischneider** [comment]
The classify-editor directive needs to expose an optional `include` attribute to allow this. Right now, it's using the `nogeom` filter though this can be removed once `include` is passed on.

Thanks for the reminder - the tests cover this use-case already so should be good to go.

**Comment by ischneider** [comment]
Forgot - for unique, we should include string/integer it seems like?

**Comment by bartvde** [comment]
right unique can be anything

**Comment by ischneider** [comment]
Seem like for unique that floating point values don't make sense?

**Comment by bartvde** [comment]
they very likely don't make sense, that is true. They should work though ;-)

**Comment by ischneider** [comment]
Fixed with 27748ba
