### ISSUE TITLE
error on load local map

### ISSUE THREAD

**Issue by bartvde** [MapStory/story-tools#164]
![screen shot 2015-02-11 at 19 31 57](https://cloud.githubusercontent.com/assets/319678/6153411/b23f62d0-b224-11e4-98e5-8428151245a3.png)

@ischneider any thoughts on this one?

**Comment by ischneider** [comment]
Not obvious what's up here. I thought I had enabled source maps but see this is not the case.

What is the stored map config?

**Comment by bartvde** [comment]
```{"id":8675321,"map":{"center":[-11225116.388676466,2794374.1027407176],"projection":"EPSG:3857","zoom":6,"layers":[{"type":"MapQuest","layer":"sat"},{"id":"geonode:african_bees_2009","title":"african_bees_2009","layerInfo":{"timeAttribute":"FIRST_YR","featureNS":"http://geonode.org/","geomType":"polygon","attributes":[{"name":"the_geom","type":"MultiPolygonPropertyType","typeNS":"http://www.opengis.net/gml"},{"name":"AREA","type":"double","typeNS":"http://www.w3.org/2001/XMLSchema"},{"name":"PERIMETER","type":"double","typeNS":"http://www.w3.org/2001/XMLSchema"},{"name":"AFRBEEP020","type":"long","typeNS":"http://www.w3.org/2001/XMLSchema"},{"name":"STATE","type":"string","typeNS":"http://www.w3.org/2001/XMLSchema"},{"name":"COUNTY","type":"string","typeNS":"http://www.w3.org/2001/XMLSchema"},{"name":"FIPS","type":"string","typeNS":"http://www.w3.org/2001/XMLSchema"},{"name":"STATE_FIPS","type":"string","typeNS":"http://www.w3.org/2001/XMLSchema"},{"name":"FIRST_YR","type":"dateTime","typeNS":"http://www.w3.org/2001/XMLSchema"}],"typeName":"geonode:african_bees_2009","featurePrefix":"geonode","times":{"start":631152000000,"end":1230768000000,"interval":31536000000}},"singleTile":false,"type":"WMS","latlonBBOX":[-120.670837402344,17.674692153930707,-64.566162109375,39.1633605957031],"url":"/geoserver/geonode/african_bees_2009/wms","params":{"LAYERS":"african_bees_2009","VERSION":"1.1.0","TILED":true,"TIME":"1990-01-01T00:00:00.000Z"}}]}}```

**Comment by bartvde** [comment]
ah I think this is a regression introduced in my #160 branch

**Comment by bartvde** [comment]
hmm but in master I am not even getting the playback tools in the app

**Comment by bartvde** [comment]
@ischneider it seems this happens when smallest is a range?

![screen shot 2015-02-16 at 17 54 43](https://cloud.githubusercontent.com/assets/319678/6215869/eada1ca0-b604-11e4-9b74-2073f2ca3ef9.png)

**Comment by bartvde** [comment]
ah this probably happens because we have not created an Interval instance

**Comment by bartvde** [comment]
I'll adapt MapConfig so that it creates the right objects
