### ISSUE TITLE
Favorites as a Geonode Plugin

### ISSUE THREAD

**Issue by zrouse-Boundless** [MapStory/story-tools#209]
As an authenticated user I would like to mark layers, documents and maps as favorites in Geonode so that I can quickly revisit them at a later date.

Acceptance Criteria:

1. Favorites button is available on Layers, Maps, and Documents
2. User profile page list favorite layers, maps, and documents in the appropriate tab under the resources group.
3. Any model that extends Resourcebase will be eligible to use the Favorites plugin
4. The plugin is available under the contrib directory
5. The favorite activity is logged to the activity stream"

**Comment by bartvde** [comment]
hey @zrouse-Boundless I am unsure if this makes sense in this bug tracker, I think it makes more sense in the https://github.com/mapstory/mapstory issue tracker

**Comment by bartvde** [comment]
story tools is just the core javascript library for dealing with story layers, story maps, timeline, annotations and story boxes

**Comment by zrouse-Boundless** [comment]
@bartvde   You are correct.  Sorry about that
