### ISSUE TITLE
In cumulative mode date label doesn't change

### ISSUE THREAD

**Issue by darinacosta** [MapStory/story-tools#250]
When using cumulative mode in the Story-tools viewer, the date label on the time bar doesn't change as new features are drawn.

**Comment by emilyashley** [comment]
This was addressed and closed in the mapstory templates by passing the playback-options to the directive's scope like this: https://github.com/MapStory/mapstory/pull/290/commits/ab65707b1d44dfda663d37b063a0f4373be02b85

**Comment by emilyashley** [comment]
oh, which branch are you on? looks like that bit `playback-options="playbackOptions"`is on `master` but missing from the `wip/composer` examples

**Comment by jonpmarino** [comment]
closing. works on production with this layer, https://mapstory.org/layers/geonode:house_sparrow_distribution0
