### ISSUE TITLE
svg icon urls for SLD

### ISSUE THREAD

**Issue by ischneider** [MapStory/story-tools#85]
To enable SVG icon coloring for geoserver, we need to:

- [x] generate SLD with appropriate URLs (e.g. `/icon/school.svg?color=red&stroke=blue` or such)
- [x] have an instance of an icon-commons endpoint available
- [x] verify with geoserver

**Comment by bartvde** [comment]
right also (fill and stroke) opacity needs to be taken as a param

**Comment by ischneider** [comment]
I've setup an online test endpoint but it should also work w/ a local one. Both support CORS to make life easier.

I'll test w/ geoserver and get the correct URL generation in tomorrow - assigned to myself

**Comment by ischneider** [comment]
This appears to generally work now.
